# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# For more information, refer to our docs: https://docs.astronomer.io/astro/environment-variables#configure-airflow-settings

airflow:
  connections:
    - conn_id: kafka_default
      conn_type: kafka
      conn_host: 77.37.44.237
      conn_schema: 
      conn_login: 
      conn_password: 
      conn_port: 9092 
      conn_extra:
        bootstrap.servers: "77.37.44.237:19092"
        group.id: "water_quality_group"
  
  config:
    webserver:
      enable_proxy_fix: true

    api:
      auth_backends: airflow.api.auth.backend.basic_auth
      access_control_allow_headers: "*"

    # Logging configuration
    loggers:
      confluent_kafka:
        level: DEBUG
    logging:
      logging_level: INFO

  pools:
    - pool_name: default_pool
      pool_slot: 10
      pool_description: Default pool