global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "water_quality_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka Exporter
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # System Health Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['system-health-exporter:9100']

  # Water Quality Metrics (from pipeline)
  - job_name: 'water-quality-metrics'
    static_configs:
      - targets: ['localhost:8000']  # Prometheus exporter port
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 60s 