data:
  min_samples: 20
  random_state: 42
  test_size: 0.2
features:
  basic_features:
  - ph
  - temperature
  - do
  interaction_features:
  - ph_temp_interaction
  - ph_do_interaction
  - temp_do_interaction
  lag_features:
  - wqi_lag_1
  - wqi_lag_2
  - wqi_lag_3
  lag_windows:
  - 1
  - 2
  - 3
  - 6
  - 12
  - 24
  rolling_features:
  - wqi_rolling_mean_3
  - wqi_rolling_std_3
  rolling_windows:
  - 3
  - 6
  - 12
  - 24
  seasonal_features:
  - is_rainy_season
  - is_dry_season
  temporal_features:
  - month_sin
  - month_cos
  - quarter_sin
  - quarter_cos
logging:
  level: INFO
  plot_results: false
  save_models: true
  save_predictions: true
lstm:
  batch_size_range:
  - 16
  - 32
  - 64
  - 128
  dropout_range:
  - 0.1
  - 0.4
  epochs: 50
  layers_range:
  - 1
  - 3
  learning_rate_range:
  - 0.0001
  - 0.01
  lr_factor: 0.5
  lr_patience: 5
  min_lr: 1e-7
  n_trials: 8
  optimizer_range:
  - adam
  - rmsprop
  - nadam
  patience: 10
  sequence_length_range:
  - 12
  - 24
  - 36
  - 48
  timeout: 300
  units_range:
  - 64
  - 128
  - 256
  - 512
  use_attention:
  - true
  - false
  use_bidirectional:
  - true
  - false
model_selection:
  lstm_weight: 1.0
  max_mae_ratio: 0.1
  max_mape: 15.0
  min_r2_score: 0.5
  stacking_weight: 1.2
  xgboost_weight: 1.0
stacking:
  enabled: true
  meta_learners:
  - ridge
  - random_forest
  rf_n_estimators: 100
  ridge_alpha: 1.0
targets:
  mae_ratio: 0.05
  mape: 10.0
  r2_score: 0.8
xgboost:
  colsample_bytree_range:
  - 0.6
  - 1.0
  cv_splits: 3
  gamma_range:
  - 0.0
  - 1.0
  learning_rate_range:
  - 0.001
  - 0.2
  max_depth_range:
  - 3
  - 12
  min_child_weight_range:
  - 1
  - 10
  n_estimators_range:
  - 100
  - 500
  n_trials: 10
  reg_alpha_range:
  - 0.0
  - 1.0
  reg_lambda_range:
  - 0.0
  - 1.0
  subsample_range:
  - 0.6
  - 1.0
  test_size_ratio: 0.2
  timeout: 150
