global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'water-quality-metrics'
    static_configs:
      - targets: ['host.docker.internal:8021']
    metrics_path: '/metrics'
    honor_timestamps: false
    scheme: http
    scrape_interval: 10s
    scrape_timeout: 5s