apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "30s"
      httpMethod: "POST"
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: prometheus
    secureJsonData: {}
    version: 1
    uid: prometheus

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: 194.238.16.14:5432
    database: wqi_db
    user: postgres
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    secureJsonData:
      password: postgres1234
    version: 1
    uid: postgresql